### ISSUE TITLE
Native component for "BVLinearGradient" does not exist.

### ISSUE THREAD

**Issue by adityasonel** [react-native-community/react-native-linear-gradient#271]
I checked both issues related to this problem, #263 and #157. But the problem is that I am still getting this error,

> Native component for "BVLinearGradient" does not exist

I don't know how to solve this. react-native-linear-gradient is linked to my project, react-native-linear-gradient  added in my project. `libBVLinearGradient.a` added in `Link Binaries with Libraries`. You can check my project screenshot below,
![screen shot 2018-04-05 at 4 59 34 pm](https://user-images.githubusercontent.com/28022451/38363569-c2ffa82a-38f2-11e8-8f34-265125d39948.png)

**Comment by poeyer** [comment]
+1

**Comment by Stas-Buzunko** [comment]
same error, followed readme

**Comment by Stas-Buzunko** [comment]
no idea how I fixed, but got it working after 1 hour.

steps I did:
1) remove node_modules
2) npm cache clean
3) remove from Podfile
4) remove from libraries and link with binaries
5) remove derived data from xcode
6) Product => clean
7) added to libraries from node_modules
8) when link with binaries => pay attention there are 2 libs with the same name, one for tvOS

**Comment by yun0926** [comment]
Will you solve it?

**Comment by blackhair** [comment]
+1

**Comment by garethiv** [comment]
I'm still experiencing this issue despite following all advice listed in this repo

**Comment by yun0926** [comment]
What is your version of react-native? Does the version affect this?

**Comment by yun0926** [comment]
It is ok.

**Comment by nooooM** [comment]
Check whether these two lines are in your 'podFile' referring cocoapods section in [README.MD](https://github.com/react-native-community/react-native-linear-gradient)
```pod 'React', :path => '../node_modules/react-native'
pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'```

Run `pod install` under `$project path/ios` before `react-native run-ios`

**Comment by longsangstan** [comment]
If anyone is having the linking problem, I recommend NOT to use pod to link the library. For some reasons I just couldn't get it work.

Here is what I did:
1) Rename the `BVLinearGradient.podspec` file to something like `BVLinearGradient.xxxpodspec`. This is to prevent `react-native link` to link the library using Podfile. See: https://facebook.github.io/react-native/docs/linking-libraries-ios.html#step-2
2) Run `react-native link`

**Comment by stevula** [comment]
Had same issue with iOS but [manually linking](https://github.com/react-native-community/react-native-linear-gradient#ios) resolved it.

**Comment by shin0602** [comment]
+1

**Comment by craig8two** [comment]
I could not get mine to work with the manual instructions from the readme either.
I struggled for ages and got it to work by doing the following:

- In xcode, click on the project, under TARGETS click on your main target, under build settings->search paths->header search paths I add the following:

`$(SRCROOT)/../node_modules/react-native-linear-gradient`

- Then I rebuilt the project, then compiled the app to simulator within xcode. 

After that I could compile the app using react-native run-ios again.

That somehow sorted it out for me.

**Comment by hakonk** [comment]
I removed `s.preserve_paths  = "**/*.js"` from the podspec of the lib, and then I managed to get it to work with cocoapods

**Comment by reehlittle** [comment]
It works with pod install!!! Just edit the 'Podfile' inside ios folder:
pod 'SRSRadialGradient', :path => '../node_modules/react-native-radial-gradient/'
and change the path to:
pod 'SRSRadialGradient', :path => '../node_modules/react-native-radial-gradient/ios'

Then run pod install again.

**Comment by friederbluemle** [comment]
Hi @reehlittle
Did you mean to post in [react-native-radial-gradient](https://github.com/surajitsarkar19/react-native-radial-gradient)? This repo is react-native-*linear*-gradient

**Comment by dblackker** [comment]
From the iOS folder, run the following:

rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
pod update

Then clean project (CMD+shift+K) and build (CMD+B).

https://gist.github.com/mbinna/4202236

**Comment by devAdrish** [comment]
<img width="301" alt="image" src="https://github.com/react-native-linear-gradient/react-native-linear-gradient/assets/83942036/4cca5bdf-0a7d-44ac-87d9-31ad41db40e0">

still exists, 
I did: remove node modules, remove pods, install modules, install pods, clean build folder, start --reset-cache, build app in the exact order, nothing is working.
Manual Linking is removed from react native so can't try that.
Running this MacBook on M2 pro, with Xcode 15.2, React Native .73, Linear Gradient 2.8.3
